# This file is the entry point to configure your own services and load the default configuration.
# If you want to remove a service, deprecate it, or change its class, you can apply the changes here.
#
# If you are *not* using the default services.yaml file in your package, you *must* pass an
# empty array to the parent constructor, or the services will be loaded twice.
#
# https://symfony.com/doc/current/configuration.html

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Layout Builder Services
    App\Block\TextBlockType:
        tags: ['app.block_type']

    App\Block\ImageBlockType:
        tags: ['app.block_type']

    App\Block\AuthorListBlockType:
        tags: ['app.block_type']

    App\Block\AuthorInfoBlockType:
        tags: ['app.block_type']

    App\Service\LayoutBuilderService:
        calls:
            - [registerBlockType, ['@App\Block\TextBlockType']]
            - [registerBlockType, ['@App\Block\ImageBlockType']]
            - [registerBlockType, ['@App\Block\AuthorListBlockType']]
            - [registerBlockType, ['@App\Block\AuthorInfoBlockType']]